[profile.default]
solc_version = "0.8.13"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
libs = ["../../node_modules", "../solecs", "../std-contracts", "../store"]
src = "test-contracts-src"
out = "test-contracts-out"
test = "test-contracts-test"
