name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and validate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Build and install CLI
        working-directory: packages/cli
        run: pnpm build && pnpm link

      - name: Generate tables
        run: pnpm tablegen

      - name: Outdated files detected, run `pnpm tablegen` and commit them
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git status
            git --no-pager diff
            exit 1
          fi

      - name: Generate gas reports
        run: pnpm gas-report

      - name: Outdated files detected, run `pnpm gas-report` and commit them
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git status
            git --no-pager diff
            exit 1
          fi
