name: Tests

on:
  push:
    branches:
      - main
      - v2
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
