name: Tests

on:
  push:
    branches:
      - main
      - v2
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run tests
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm test
